import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ApolloWrapper } from './providers/ApolloWrapper'
import { Header } from '@/widgets/Header'
import { Alert } from '@filippsm/ui-kit-mypixelgram-demo'

const inter = Inter({
   variable: '--font-inter',
   subsets: ['latin'],
})

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body className={`${inter.variable} min-h-screen`}>
            <ApolloWrapper>
               <Header />
               {children}
               <Alert />
            </ApolloWrapper>
         </body>
      </html>
   )
}
